# Project: LinkArray
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = array.o
LINKOBJ  = array.o
LIBS     = -L"D:/developer_tools/C++/Dev-C++/MinGW64/lib" -L"D:/developer_tools/C++/Dev-C++/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/developer_tools/C++/Dev-C++/MinGW64/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/developer_tools/C++/Dev-C++/MinGW64/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = LinkArray.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

array.o: array.c
	$(CC) -c array.c -o array.o $(CFLAGS)
