# Project: Student
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainStudent.o read.o
LINKOBJ  = mainStudent.o read.o
LIBS     = -L"D:/developer_tools/C++/Dev-C++/MinGW64/lib" -L"D:/developer_tools/C++/Dev-C++/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/developer_tools/C++/Dev-C++/MinGW64/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/developer_tools/C++/Dev-C++/MinGW64/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/developer_tools/C++/Dev-C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Student.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

mainStudent.o: mainStudent.c
	$(CC) -c mainStudent.c -o mainStudent.o $(CFLAGS)

read.o: read.c
	$(CC) -c read.c -o read.o $(CFLAGS)
